### ISSUE TITLE
Std file of dicts vs MW submissions

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#380]
#363 to #379 issues submitted corrections to various dictionaries.
The composite file for uploading in standard format is as below
```
SKD:kacCAA:kacCA:t
VEI:kusurubindaOddalaki:kusurubindaOddAlaki:t
CAE:sarvAnuikramaRI:sarvAnukramaRI:t
ACC:uTAnadvAdaSIvratakalpa:utTAnadvAdaSIvratakalpa:t
MW72:acCE:acCai:t
PUI:aparARhA:aparAhRA:t
GST:aparAhletana:aparAhRetana:t
VEI:amAvAsyaSARdilyAyana:amAvAsyaSARqilyAyana:p
YAT:arTopekzepaka:arTopakzepaka:p
PUI:Anhikakrama:Ahnikakrama:p
PUI:janhu:jahnu:p
PUI:janhugaRa:jahnugaRa:p
PUI:jAnhavI:jAhnavI:p
INM:mitrAvaruRayohputraH:mitrAvaruRayoHputraH:p
BUR:mimArqizAmi:mimarqizAmi:t
PUI:vanhi:vahni:p
PUI:vanhijvAla:vahnijvAla:p
PUI:vanhivAsa:vahnivAsa:p
PUI:vanhivAsinI:vahnivAsinI:p
PUI:vAqavavanhi:vAqavavahni:p
CAE:vizaRravadana:vizaRRavadana:t
MCI:SAlipIRqa:SAlipiRqa:p
MW72:aBicihnya:aBicihnaya:t
MW72:aBisaNkruD:aBisaMkruD:t
MW72:aBisaNkruS:aBisaMkruS:t
VCP:UdDvaka:UrdDvaka:p
VCP:UrdDakaca:UrDvakaca:p
VCP:UrdDakaRWa:UrDvakaRWa:p
VCP:UrdDakarmman:UrDvakarmman:p
VCP:UrdDamAna:UrDvamAna:p
PUI:EndrEzwi:EndraIzwi:t
ACC:OdIcryaprakASegotrapravaroccAraH:OdIcyaprakASegotrapravaroccAraH:t
ACC:gaNgAnandakavondra:gaNgAnandakavIndra:t
ACC:gOtamIgaNgAmAhatmya:gOtamIgaNgAmAhAtmya:t
PE:pativratAmAhatmyaparva:pativratAmAhAtmyaparva:p
SHS:brAhmta:brAhmya:t
ACC:vESvatmyarahasya:vESvAtmyarahasya:t
WIL:saumdvahat:samudvahat:t
CAE:brAhymya:brAhmya:p
ACC:tkAvAda:ktvAvAda:t
PD:aDaHSayy:aDaHSayyA:t
PUI:cidvanhi:cidvahni:p
PUI:janhu:jahnu:p
PUI:janhugaRa:jahnugaRa:p
PUI:jAnhavI:jAhnavI:p
PUI:maDyAnhA:maDyAhnA:p
```

**Comment by funderburkjim** [comment]
Thanks -- this standard file helps.

In fact, since you are doing a lot of these  (most of #381 - #407 also seem of this ilk) ,  might I request:
* make one or more summary standard files like above for these
* Plan to let me know when you've done with this round of study
   * Then, I'll aggregate all the standard files into one big standard file, and install all in one
      session.

**Comment by funderburkjim** [comment]
> MW72:aBisaNkruD:aBisaMkruD:t
MW72:aBisaNkruS:aBisaMkruS:t

I don't see any reason to change these two;  the homorganic nasal 'N' before 'k' is gramattically acceptable.   In both cases,
the Devanagari of the text shows 'M', while the companion IAST shows 'N' (the two are inconsistent).
![image](https://user-images.githubusercontent.com/6393033/30305623-db216aae-9741-11e7-8db7-42efc00994ce.png)

On next page,  the homorganic nasals are used in Devanagari as well as IAST.

Probably the anusvara in Devanagari for aBisaNkruD (S) is some kind of print error, since preceding several words  (nasal before sibilants) use anusvara.

**Comment by funderburkjim** [comment]
> PUI:EndrEzwi:EndraIzwi:t

I think it should be Endra**i**zwi   (Endra + izwi).

**Comment by funderburkjim** [comment]
> VCP:UrdDakaRWa:UrDvakaRWa:p

I think no change required.  ( I'm assuming UrDvakaRWa: is a typo and Ur**d**DvakaRWa was intented).

Both forms are given.  We currently have 'UrdDvakaRWa' as the alternate of UrdDakaRWa.

![image](https://user-images.githubusercontent.com/6393033/30349993-feccef72-97e2-11e7-822f-ce968776cb16.png)

**Comment by gasyoun** [comment]
> I think no change required. Similar reason.

@SergeA ?

**Comment by SergeA** [comment]
ūrddha(rddhva)karmman - this one is clear enough in the scan. Others have in brackets something indistinct, but should be similar. So rddha/rddhva.

**Comment by drdhaval2785** [comment]
There is NO such word as UrDa. 
It is UrDva only. And by a grammatical rule it gets converted to UrdDva.

So no question of UrDa survives. If it is there, it is print error.

Needs correction affirmatively.

**Comment by drdhaval2785** [comment]
> aBisaNkruD, aBisaNkruS

These two need corrections, because everywhere Monier uses M. These are the only two digitization errors. Print version has M.
So whether it is grammatically valid form or not has no bearing in this case. In any case normalization will lead to this entry in web display. It is about convention violation.

**Comment by drdhaval2785** [comment]
> Endraizwi (Endra + izwi).

Agree

**Comment by funderburkjim** [comment]
> because everywhere Monier uses M. 

Aren't you thinking of AP90?   MW uses both homorganic nasals and anusvAra.  Although his rule for when to use which is either inconsistent or obscure.

**Comment by drdhaval2785** [comment]
Yes. You are right. I see the problem now.
It is a print error on part of MW72.
Actually he should have used 'N' but erroneously used 'M'.
So no change is needed. Only need to document somewhere that this is a print error (which is already corrected).

**Comment by funderburkjim** [comment]
> There is NO such word as UrDa.

Here's some information from hwnorm1c that challenges the 'no UrDa' contention:
```
 145874:UrdDa:UrdDa:BOP,BUR,SHS,VCP,WIL,YAT;UrdDaH:SKD
 145875:UrdDaka:UrdDaka:SHS,VCP,WIL,YAT;UrdDakaH:SKD
 145876:UrdDakaca:UrdDakaca:VCP
 145877:UrdDakaRWa:UrdDakaRWa:VCP
 145878:UrdDakarman:UrdDakarmman:VCP
 145879:UrdDamanTin:UrdDamanTin:VCP,YAT
 145880:UrdDamAna:UrdDamAna:VCP

 145881:UrdDva:UrdDva:BOP,SHS,VCP,WIL,YAT;UrdDvaH:SKD
 145882:UrdDvaka:UrdDvaka:SHS,VCP,WIL,YAT;UrdDvakaH:SKD
```
I haven't examined these entries.


One other piece of information that indirectly *supports* the 'no UrDa' claim is from PD:
```
anūrdha [p= 6-3339] : .anūrdha¦ (an-ūrdha) [w. r. for anūrdhva] MediK. 140. 105; 158. 21. [L=84998]
```

I'm still not convinced we should change all the `UrdDa` cases to 'UrdDva`  (in VCP as well as the other
dictionaries mentioned above).

**Comment by drdhaval2785** [comment]
> UrdDa controversy

SKD actually records that this is 'without v'.

![capture](https://user-images.githubusercontent.com/5755132/30359908-b465c7ea-986b-11e7-9a60-da1c438d2fb7.png)

**Comment by SergeA** [comment]
> There is NO such word as UrDa.
> It is UrDva only. And by a grammatical rule it gets converted to UrdDva.
> So no question of UrDa survives. If it is there, it is print error.
> Needs correction affirmatively.

I'm against such changes. The authors clearly show they think there IS such word as ūrdha(ūrddha). Perhaps it is not correct. MW includes the spelling ūrdha as incorrect for ūrdhva. But we must remember that the dictionary represent authors' position, not ours. So if the authors prefer an incorrect spelling we must respect their opinion.

**Comment by gasyoun** [comment]
> So if the authors prefer an incorrect spelling we must respect their opinion.

But add a note in the comment, agree?

**Comment by funderburkjim** [comment]
> But add a note in the comment, agree?

Not sure what 'comment' you are thinking of.  The only place I can think of is somehwere in [CORRECTIONS/dictionaries/vcp](https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/dictionaries/VCP), possibly in vcp_printchange.txt or possibly in a new file named vcp_comments.txt.  One of these ok with you, @gasyoun ?

**Comment by gasyoun** [comment]
> possibly in vcp_printchange.txt 

Was thinking of it.

**Comment by funderburkjim** [comment]
> aBisaNkruD, S  Only need to document somewhere

The change to homorganic nasal was made in a batch of corrections of [Jan 2015](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/71#issuecomment-71345091).

Relevant lines of manualByLine02.txt:
Note that the 'typo' is wrong here.
```
; 01/25/2015 typo  aBisaMkruD -> aBisaNkruD
16348 old <P>.{#aBisaMkruD#}¦ {%abhi-san4-krudh (-sam-krudh),%}
16348 new <P>.{#aBisaNkruD#}¦ {%abhi-san4-krudh (-sam-krudh),%}
; 01/25/2015 typo  aBisaMkruS -> aBisaNkruS
16354 old <P>.{#aBisaMkruS#}¦ {%abhi-san4-krus4 (-sam-krus4),%} cl. 1.
16354 new <P>.{#aBisaNkruS#}¦ {%abhi-san4-krus4 (-sam-krus4),%} cl. 1.
```

Have documented as print change in [mw72_printchange.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/MW72/mw72_printchange.txt).

Notes:
* Not sure why not documented as print change back in 2015. Maybe we had not understood as fully
the importance of such documentation at that time
* There may be other undocumented print changes from that 2015 batch of changes.  This could be
   ascertained by examining #71 and/or manualByLine02.txt.
* It is a minor miracle to find such detailed records of things done (or undone)  almost 3 years ago.

**Comment by funderburkjim** [comment]
> Documenting retention of UrdDa

[vcp_printchange.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/VCP/vcp_printchange.txt)  has this (see current bottom of file).

Note that the preferred 'UrdDva' spellings are part of vcp_hwextra.txt as alternate headword spellings, hence user searching will find this spelling.

**Comment by gasyoun** [comment]
> It is a minor miracle to find such detailed

With you on board, it's an ordinary miracle, as usual :jamaica:

**Comment by drdhaval2785** [comment]
Three test checks in different dictionaries confirm that the changes are incorporated.
