### ISSUE TITLE
AP90 - Compounds stated twice

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/CORRECTIONS#434]
There are three places in the whole of AP dictionary, where the word -Comp is stated twice.
They are [ayAta]https://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/web/webtc/servepdf.php?page=0157-b), [muKaM](https://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/web/webtc/servepdf.php?page=0868-b) and [sarpis](https://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/web/webtc/servepdf.php?page=1108-c)

Not sure whether they are print errors or deliberate.
@SergeA may like to investigate these cases.

**Comment by SergeA** [comment]
I do not see any sense in those double "Comp" marks. 
I've checked by edition 3 (1924) - all 3 cases are corrected there without duplication.
So it looks like print error of the 1st ed.

**Comment by gasyoun** [comment]
@drdhaval2785 your turn again?

**Comment by gasyoun** [comment]
**H1523 re-check of the three named cases in current `ap90.txt`**

| Case | Status |
|------|--------|
| ayAta (0157-b) | Single `{@--Comp.@}` only — no bare second Comp |
| muKaM (0868-b) | Single `{@--Comp.@}` only |
| **sarpis (1108-c)** | Still has bare `--Comp.` after first compound list: `…seas. --Comp. {#--AsutiH#}` |

Also still present elsewhere (not in original three): bare `--Comp.` at plavaMgamaH (~0782) and `--COMP.` near dig- compounds (~270173).

**Next:** queue sarpis (and optional siblings) as csl-orig text-correction via monthly cologne-correction-queue — not a display-layer fix. Issue stays open until those lines land in csl-orig.

**Comment by gasyoun** [comment]
**H1523: sarpis case queued for monthly csl-orig batch**

Validated change (local queue only — no csl-orig push):

```
257097 old of the seven seas. --Comp. {#--AsutiH#}
257097 new of the seven seas. {#--AsutiH#}
```

- Path: `csl-corrections/batch_pending/dictionaries/ap90/change_ap90_1.txt`
- Validation: `updateByLine` applied 1 change; `make_xml.py` → **All records parsed by ET**
- Promotes with `/cologne-batch-pr`

ayAta / muKa remain single `{@--Comp.@}` (already clean). Optional siblings (plavaMgama bare `--Comp.`, dig `--COMP.`) not queued this pass.

**Comment by gasyoun** [comment]
**H1523 queue update**

| Case | Action |
|------|--------|
| ayAta / muKa | Already single `{@--Comp.@}` — clean |
| sarpis | `change_ap90_1.txt` removes bare second `--Comp.` (XML already shows one Comp header) |
| plavaMgama (not in original 3) | `change_ap90_2.txt` bare `--Comp.` → `{@--Comp.@}` (make_xml was leaving literal `-Comp.` text) |
| harita dig-compounds | same file: `--COMP.` → `{@--Comp.@}` |

All three AP90 lines: combined validation **All records parsed by ET**.

Queue: `csl-corrections/batch_pending/dictionaries/ap90/` — promote via `/cologne-batch-pr`.

**Comment by gasyoun** [comment]
**H1523 display + queue**

1. **Display (immediate):** websanlexicon + apidev promote leftover `-Comp.` text to a Comp. header
   - https://github.com/sanskrit-lexicon/csl-websanlexicon/pull/106
   - https://github.com/sanskrit-lexicon/csl-apidev/pull/98
2. **Source (monthly batch):** `batch_pending/dictionaries/ap90/change_ap90_{1,2}.txt` — sarpis + plavaMgama + harita

**Comment by gasyoun** [comment]
**H1523 close — display fixed; source queued**

**Named cases:**
| Case | Status |
|------|--------|
| ayAta / muKa | Single `{@--Comp.@}` in current ap90.txt |
| sarpis | XML already emits one Comp. header; bare second `--Comp.` queued as `change_ap90_1.txt` |

**Display (merged):** leftover literal `-Comp.` (e.g. plavaMgama) promoted to Comp. header
- https://github.com/sanskrit-lexicon/csl-websanlexicon/pull/106
- https://github.com/sanskrit-lexicon/csl-apidev/pull/98

**Source hygiene (monthly batch):** `batch_pending/dictionaries/ap90/change_ap90_{1,2}.txt` (sarpis + plavaMgama + harita).

Closing the bug; remaining work is batch promotion only.
